### PR TITLE
Updates override classname to proper class name

### PR DESCRIPTION
**Pull request by dillonhafer**
Class name was changed back in 1f2bd172d60f5ade65a50a5c8dd770826a0ffa61

### CODE REVIEW

**Comment by dillonhafer** [comment]
It's not very clear why you closed this PR.

Please explain what closing solves. I don't understand.. Thanks

**Comment by yairEO** [comment]
well, because it was not clear what this all means. you did not explain what is the current problem and why your changes will work better..

**Comment by dillonhafer** [comment]
Ahh ok.

This change updates the override css class name to the update proper class name to make the README accurate. In its current state, the README is inaccurate to proper class name for overrides.

Currently the readme state:

`#pbOverlay .imageWrap` is the class to use when overriding default styles. This is not the case, it should say `#pbOverlay .pbWrapper`

Users who try to override their CSS will be unable to unless they see  that the css class name was changed way back in 1f2bd17

This update to the README should help provide a more accurate and helpful way to find the proper styles a user should use to override the default class names styles using CSS.

**Comment by yairEO** [comment]
@dillonhafer  - But the README doesn't currently states that..

**Comment by dillonhafer** [comment]
The README did at the time of the PR 6 months ago. If you had mentioned that this was previously resolved it might have been clearer why you closed it.

**Comment by yairEO** [comment]
@dillonhafer - Sorry I was unclear that I resolved this... my bad..

**Pull request closed without merging**
